<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>ModularData.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Orders\Orders.Entities.csproj" ModulithModule="true" />
    <ProjectReference Include="..\Modules\Customers\Customers.Entities.csproj" ModulithModule="true" />
    <ProjectReference Include="..\Modules\CustomersApi\CustomersModule.csproj" ModulithModule="true" />
    <ProjectReference Include="..\Modules\Billing\BillingModule.csproj" ModulithModule="true" />
  </ItemGroup>

</Project>
