// Builds a context for `dotnet ef` against the union of every module.
//
// dotnet ef DOES build the host, so HostingStartup runs and the model would follow
// HOSTINGSTARTUPASSEMBLIES as it stands in the shell that ran the command: empty when it is unset,
// one topology's tables when it is not, and no error either way. Naming every module instead makes
// the migration the same on every machine and in CI.
//
// KnownModules is generated by FusionModules from this project's references, so the list cannot
// fall behind the project file. Dependencies come first, which puts a composing module after the
// modules it joins.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using FusionModules;

namespace Host;

internal sealed class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
{
    public ApplicationDbContext CreateDbContext(string[] args)
    {
        var configuration = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json", optional: true)
            .AddEnvironmentVariables()
            .AddInMemoryCollection(ModuleBase.CreateModuleRegistry(KnownModules.Names))
            .Build();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseNpgsql(configuration.GetConnectionString("Postgres"))
            .ReplaceService<IModelCacheKeyFactory, ModuleAwareModelCacheKeyFactory>()
            .Options;

        return new ApplicationDbContext(options, configuration);
    }
}
