<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ModularData.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Host\Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Orders\Orders.Entities.csproj" ModulithModule="true" />
    <ProjectReference Include="..\Modules\Customers\Customers.Entities.csproj" ModulithModule="true" />
    <ProjectReference Include="..\Modules\CustomersApi\CustomersModule.csproj" ModulithModule="true" />
    <ProjectReference Include="..\Modules\Billing\BillingModule.csproj" ModulithModule="true" />
  </ItemGroup>

</Project>
