<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sample.Mvc.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Host\Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ModulithModule Include="..\Modules\Dashboard\DashboardModule.csproj" />
    <ModulithModule Include="..\Modules\Status\StatusModule.csproj" />
  </ItemGroup>

</Project>
