<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Modules\Checkout\CheckoutModule.csproj" />
    <ProjectReference Include="..\Modules\Pricing\PricingModule.csproj" />
    <ProjectReference Include="..\Modules\PricingApi\PricingApiModule.csproj" />
    <ProjectReference Include="..\Modules\PricingClient\PricingClientModule.csproj" />
  </ItemGroup>

</Project>
